# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fortnite Stats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fortnite Stats
pod 'Charts'
  target 'Fortnite StatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fortnite StatsUITests' do
    # Pods for testing
  end

end
